<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kelola_barang_masuk_model extends CI_Model
{

    public $table = 'kelola_barang_masuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('id_supplier', $q);
        $this->db->or_like('harga_barang', $q);
        $this->db->or_like('jml_barang_masuk', $q);
        $this->db->or_like('tgl_masuk', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select("kelola_barang_masuk.*,users.first_name,users.last_name,kelola_supplier.nama");
        $this->db->join('users','kelola_barang_masuk.id_user=users.id');
        $this->db->join('kelola_supplier','kelola_barang_masuk.id_supplier=kelola_supplier.id');
        $this->db->order_by('kelola_barang_masuk.id', $this->order);
        // $this->db->like('id', $q);
        $this->db->or_like('users.first_name', $q);
        $this->db->or_like('users.last_name', $q);
        $this->db->or_like('kelola_supplier.nama', $q);
        // $this->db->or_like('id_supplier', $q);
        // $this->db->or_like('harga_barang', $q);
        // $this->db->or_like('jml_barang_masuk', $q);
        // $this->db->or_like('tgl_masuk', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }
    function get_limit_data_print_bm()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id');
        $this->db->or_like('id_user');
        $this->db->or_like('id_supplier');
        $this->db->or_like('harga_barang');
        $this->db->or_like('jml_barang_masuk');
        $this->db->or_like('tgl_masuk');
        return $this->db->get($this->table)->result();
    }
    function laporan_barang_masuk_total($q = NULL, $dari, $sampai)
    {
        $this->db->from($this->table);
        $this->db->where('tgl_masuk >=', $dari);
        $this->db->where('tgl_masuk <=', $sampai);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function laporan_barang_masuk($limit, $start = 0, $q = NULL, $dari, $sampai)
    {
        $this->db->where('tgl_masuk >=', $dari);
        $this->db->where('tgl_masuk <=', $sampai);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    // delete bulkdata
    function deletebulk()
    {
        $data = $this->input->post('msg_', TRUE);
        $arr_id = explode(",", $data);
        $this->db->where_in($this->id, $arr_id);
        return $this->db->delete($this->table);
    }
}

/* End of file Kelola_barang_masuk_model.php */
/* Location: ./application/models/Kelola_barang_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-06-30 10:22:17 */
/* http://harviacode.com */